//
//  LocalizedType.swift
//
//  Created by tkgstrator on 2023/06/04
//  Copyright @2023 Magi, Corporation. All rights reserved.
//

import Foundation

public enum LocalizedType: String, CaseIterable, Identifiable {
    public var id: String { rawValue }

    /// About
    case CommonAbout
    /// クレジット
    case CommonAppCredit
    /// バージョン
    case CommonAppVersion
    /// 外観
    case CommonAppearances
    /// アプリ
    case CommonApplication
    /// 圧縮(ZIP)
    case CommonBackupCompress
    /// データベースのバックアップを出力します。
    case CommonBackupMessage
    /// 非圧縮(JSON)
    case CommonBackupPlain
    /// バックアップ
    case CommonBackupResults
    /// キャンセル
    case CommonCancel
    /// 報酬
    case CommonCheckInReward
    /// ガチアサリ
    case CommonClamBlitz
    /// 閉じる
    case CommonClose
    /// ビッグラン
    case CommonCoopBigRun
    /// バイトチームコンテスト
    case CommonCoopTeamContest
    /// QRコードは、株式会社デンソーウェーブの登録商標です。
    case CommonCopyrightQrCode
    /// UI/UXデザイン
    case CommonCreditDesign
    /// 開発
    case CommonCreditDevelop
    /// テスト
    case CommonCreditTest
    /// ダークモード
    case CommonDarkMode
    /// データ管理
    case CommonDataManagement
    /// データベース
    case CommonDatabase
    /// 決定
    case CommonDecide
    /// デベロッパの回答
    case CommonDeveloperAnswer
    /// ダウンロード
    case CommonDownload
    /// おわる
    case CommonEnd
    /// よくあるご質問
    case CommonFAQ
    /// ゲーミングモード
    case CommonGamingMode
    /// はてな
    case CommonGearPowerBlank
    /// 過去に配布されていたQRコードの報酬を取得します。
    case CommonGetCheckInReward
    /// 金イクラ
    case CommonGoldenEggs
    /// ホーム
    case CommonHome
    /// イカリング2
    case CommonIkaring2
    /// イカリング３
    case CommonIkaring3
    /// 無効
    case CommonInvalid
    /// 0
    case CommonLanguageCode
    /// 言語
    case CommonLanguages
    /// ライセンス
    case CommonLicense
    /// ja-JP
    case CommonLocale
    /// ログファイル
    case CommonLogSize
    /// サポートされていないバージョンでバックアップされたリザルトのため復元できませんでした。
    case CommonMinimumVersion
    /// マイページ
    case CommonMyPage
    /// ロード中
    case CommonNowLoading
    /// 概要
    case CommonOverview
    /// イクラ
    case CommonPowerEggs
    /// プライバシーポリシー
    case CommonPrivacyPolicy
    /// ひっぱって更新
    case CommonPullToRefresh
    /// ガチホコバトル
    case CommonRainmaker
    /// フォーム
    case CommonRequestForm
    /// バグ修正
    case CommonRequestFormBug
    /// 内容
    case CommonRequestFormContent
    /// 改善案
    case CommonRequestFormEnhancement
    /// 機能追加
    case CommonRequestFormFeature
    /// タイトル
    case CommonRequestFormTitle
    /// 種類
    case CommonRequestFormType
    /// このアプリを利用するにはニンテンドーアカウントでログインする必要があります。
    case CommonRequiredSignIn
    /// この機能を利用するにはiOS16以上にアップデートする必要があります。
    case CommonRequirediOS16
    /// 送信
    case CommonRequsetFormSubmit
    /// リストア
    case CommonRestore
    /// リザルト復元に失敗しました。未サポートの形式またはファイルが改ざんされているため署名が一致しません。
    case CommonRestoreFailureMessage
    /// ファイルアプリからリストアするファイルを選択してください。
    case CommonRestoreMessage
    /// リザルト復元に成功しました。
    case CommonRestoreSuccessMessage
    /// リザルト件数
    case CommonResultsCount
    /// デバッグ
    case CommonRoleDebuger
    /// 開発
    case CommonRoleDeveloper
    /// テスト
    case CommonRoleTester
    /// 翻訳
    case CommonRoleTranslator
    /// 保存しました
    case CommonSaveToPhotoLibrary
    /// スケジュール同期
    case CommonScheduleSync
    /// スケジュールサーバーから過去のスケジュールを取得します
    case CommonScheduleSyncMessage
    /// シェア
    case CommonShare
    /// ログ送信
    case CommonShareLog
    /// 開発者にログを送信します。エラー発生時にログファイルを送信していただくことで、開発者が原因特定と修正するのが楽になります。ログファイルには個人を特定する一切の情報は含まれていません。
    case CommonShareLogMessage
    /// ログイン
    case CommonSignIn
    /// ログアウト
    case CommonSignOut
    /// ニンテンドーアカウントとの連携を解除します
    case CommonSignOutMessage
    /// ログアウト成功しました
    case CommonSignOutSuccessfully
    /// ソースコード
    case CommonSourceCode
    /// ガチエリア
    case CommonSplatZones
    /// ガチヤグラ
    case CommonTowerControl
    /// トリカラアタック
    case CommonTricolor
    /// トリカラマッチ
    case CommonTricolorMatch
    /// ナワバリバトル
    case CommonTurfWar
    /// アプリをアップデートしてください
    case CommonUpdateRequired
    /// アップロード
    case CommonUpload
    /// Safariの認証を利用する
    case CommonUseSecureSession
    /// 端末の設定を利用する
    case CommonUseSystemTheme
    /// ユーザーデータ
    case CommonUserData
    /// 有効
    case CommonValid
    /// ログ消去
    case CommonWipeLog
    /// 保存されている全てのログを消去します。
    case CommonWipeLogMessage
    /// リザルト消去
    case CommonWipeResults
    /// 保存されている全てのリザルトを消去します。
    case CommonWipeResultsMessage
    /// はてな
    case CommonWpnNotfound
    /// レビューを書く
    case CommonWriteReview
    /// X-ProductVersion
    case CommonXProductVersion
    /// X-WebViewVer
    case CommonXWebViewVer
    /// 出現数
    case CoopHistoryAvailable
    /// 出現したオカシラシャケ
    case CoopHistoryAvailableBoss
    /// 平均クリアWAVE数
    case CoopHistoryAverageClearWaves
    /// ビッグラン
    case CoopHistoryBigrun
    /// クリアボーナス
    case CoopHistoryBonus
    /// オカシラシャケ出現！
    case CoopHistoryBossAvailable
    /// Clear!!
    case CoopHistoryClear
    /// なかまの平均
    case CoopHistoryCrewAvgResult
    /// なかま
    case CoopHistoryCrewResult
    /// キケン度
    case CoopHistoryDangerRatio
    /// 助けられた回数
    case CoopHistoryDeathCount
    /// オカシラシャケ撃破！
    case CoopHistoryDefeatBoss
    /// 倒したオカシラシャケ
    case CoopHistoryDefeatBossCount
    /// 倒した！
    case CoopHistoryDefeated
    /// オオモノシャケをたおした数
    case CoopHistoryDefeatedCount
    /// 倒したオオモノシャケ
    case CoopHistoryDefeatedEnemies
    /// ※カッコ内の数字は自分で倒した数です
    case CoopHistoryDefeatedEnemiesGuide
    /// 集めたイクラ
    case CoopHistoryDeliverCount
    /// オオモノシャケ
    case CoopHistoryEnemy
    /// 推定値
    case CoopHistoryEstimatedValue
    /// イベントクリア率
    case CoopHistoryEventClearRatio
    /// イベント発生率
    case CoopHistoryEventFrequency
    /// EX-WAVE
    case CoopHistoryExWave
    /// Failure
    case CoopHistoryFailure
    /// GJ!
    case CoopHistoryGj
    /// バイトヒストリー一覧に戻る
    case CoopHistoryGoToStats
    /// 集めた金イクラ
    case CoopHistoryGoldenDeliverCount
    /// 称号
    case CoopHistoryGradeId
    /// 評価ポイント
    case CoopHistoryGradePoint
    /// 最高きろく
    case CoopHistoryHighestRecord
    /// ハイスコア
    case CoopHistoryHighestScore
    /// バイトヒストリー
    case CoopHistoryHistory
    /// 獲得ポイント
    case CoopHistoryJobPoint
    /// 評価レート
    case CoopHistoryJobRatio
    /// クマサンポイントカード
    case CoopHistoryKumaPointCard
    /// 最新のバイトへ
    case CoopHistoryLatest
    /// 現在の期間限定ポイント
    case CoopHistoryLimitedPoint
    /// 今月のギア
    case CoopHistoryMonthlyReward
    /// 次のバイト
    case CoopHistoryNext
    /// NG
    case CoopHistoryNg
    /// バイトヒストリーがありません
    case CoopHistoryNoData
    /// バイトヒストリーを表示できません
    case CoopHistoryNotAvailable
    /// 閲覧できるバイトヒストリーは、最新の50戦までです。
    case CoopHistoryNotAvailableDescription
    /// 倒せなかった...
    case CoopHistoryNotDefeated
    /// 総合きろく
    case CoopHistoryOverallRecord
    /// バイト回数
    case CoopHistoryPlayCount
    /// なかま
    case CoopHistoryPlayerCrew
    /// あなた
    case CoopHistoryPlayerResult
    /// あなた
    case CoopHistoryPlayerYou
    /// 前のバイト
    case CoopHistoryPrevious
    /// プライベート
    case CoopHistoryPrivate
    /// スタッフ募集！
    case CoopHistoryRecruit
    /// 簡単
    case CoopHistoryRecruitTag1
    /// イクラ集め
    case CoopHistoryRecruitTag2
    /// ～イカした制服でイクラ集め～
    case CoopHistoryRecruitTitle
    /// いつものバイト
    case CoopHistoryRegular
    /// 現在のポイント
    case CoopHistoryRegularPoint
    /// 助けた回数
    case CoopHistoryRescueCount
    /// たすけてもらったかいすう
    case CoopHistoryRescuedCount
    /// リザルト件数
    case CoopHistoryResultsCount
    /// ウロコ
    case CoopHistoryScale
    /// ドウウロコ
    case CoopHistoryScaleBronze
    /// キンウロコ
    case CoopHistoryScaleGold
    /// ギンウロコ
    case CoopHistoryScaleSilver
    /// バイトスコア
    case CoopHistoryScore
    /// スケジュールを見る
    case CoopHistorySeeSchedule
    /// オカシラゲージ
    case CoopHistorySmellMeter
    /// 支給率
    case CoopHistorySuppliedRatio
    /// 支給ブキ
    case CoopHistorySupplyWeapon
    /// バイトチームコンテスト
    case CoopHistoryTeamContest
    /// チームポイントカード
    case CoopHistoryTeamPointCard
    /// チーム
    case CoopHistoryTeamResult
    /// サーモンラン
    case CoopHistoryTitle
    /// るいけいポイント
    case CoopHistoryTotalPoint
    /// 推定値を表示
    case CoopHistoryUseEstimatedValue
    /// WAVE
    case CoopHistoryWave
    /// 干潮
    case CoopHistoryWaveLevel0
    /// 普通
    case CoopHistoryWaveLevel1
    /// 満潮
    case CoopHistoryWaveLevel2
    /// Waves
    case CoopHistoryWaveResult
    /// 平均
    case CoopRecordAverageScore
    /// 最高
    case CoopRecordHighestScore
    /// ホームに戻る
    case ErrorBackToHome
    /// 現在利用できません。しばらくお待ちください
    case ErrorCurrentlyNotAvailable
    /// エラー
    case ErrorError
    /// エラーが発生しました
    case ErrorErrorOccurred
    /// 読みこみに失敗しました
    case ErrorErrorReopen
    /// バックアップの署名が一致しなかったため復元できませんでした。リザルトが改ざんされている可能性があります。
    case ErrorInvalidSignature
    /// ただいまサーバーのメンテナンス中です。時間をおいて再度アクセスしてください。
    case ErrorMaintenanceDescription
    /// しばらくお待ちください
    case ErrorMaintenanceTitle
    /// 再読みこみ
    case ErrorReload
    /// 実測値
    case RecordActualValue
    /// 平均きろく
    case RecordAverageScore
    /// 最後に遊んだ
    case RecordLatestPlayed
    /// よく使う
    case RecordLatestUsed
    /// メイン
    case RecordMain
    /// じゅくれん度アップまで
    case RecordNextSkillLevel
    /// じゅくれん度
    case RecordSkillLevel
    /// 並び替え
    case RecordSort
    /// スペシャル
    case RecordSpecial
    /// ステージのきろく
    case RecordStageRecord
    /// ステージ
    case RecordStageRecordAppName
    /// サブ
    case RecordSub
    /// きろく
    case RecordTitle
    /// 塗りポイント
    case RecordTurfPoint
    /// 遊んでないステージ
    case RecordUnplayedStages
    /// 未所持のブキ
    case RecordUnusedWeapons
    /// チョーシ
    case RecordVibes
    /// ブキのきろく
    case RecordWeaponRecord
    /// ブキ
    case RecordWeaponRecordAppName
    /// 勝利数
    case RecordWinCount
    /// 権利表記
    case SettingsAcknowledgements
    /// 設定
    case SettingsAppName
    /// クレジット
    case SettingsCredits
    /// エキスパンション・パス 購入サイトへ
    case SettingsExpansionPass
    /// 設定
    case SettingsTitle
    /// バンカラマッチ
    case StageScheduleBankara
    /// オープン
    case StageScheduleBankaraOpen
    /// チャレンジ
    case StageScheduleBankaraOpenChallenge
    /// サーモンラン
    case StageScheduleCoop
    /// NOW OPEN！
    case StageScheduleCoopCurrentPeriodStart
    /// イベントマッチ
    case StageScheduleEvent
    /// いま
    case StageScheduleEventCurrentSchedule
    /// そのつぎ
    case StageScheduleEventFuture
    /// 開催中！
    case StageScheduleEventHolding
    /// 次回
    case StageScheduleEventNext
    /// つぎ
    case StageScheduleEventNextSchedule
    /// スケジュールが未定です
    case StageScheduleEventNoData
    /// ?????
    case StageScheduleEventUnknownData
    /// イベント開催！
    case StageScheduleEventmatch
    /// そのつぎ
    case StageScheduleFuture
    /// Webブラウザが開きます
    case StageScheduleGuideOpenBrowser
    /// つぎ
    case StageScheduleNext
    /// ビッグラン接近中！
    case StageScheduleNoticeBigrun
    /// バイトチームコンテスト開催予告！
    case StageScheduleNoticeLimited
    /// フェスマッチ開催中！
    case StageScheduleNowClosed
    /// オープン！
    case StageScheduleOpen
    /// ビッグラン発生中！
    case StageScheduleOpenBigrun
    /// バイトチームコンテスト開催中！
    case StageScheduleOpenLimited
    /// プライベートマッチ
    case StageSchedulePrivate
    /// ビッグランがやってくる！！バイト大募集
    case StageScheduleRecruit
    /// バイトチームコンテスト！チームを組んで参加しよう！
    case StageScheduleRecruitTeamContest
    /// レギュラーマッチ
    case StageScheduleRegular
    /// ルールを見る
    case StageScheduleRules
    /// 詳しいルールはこちら
    case StageScheduleSeeAllRules
    /// ランダム
    case StageScheduleSuppliedWeaponRandom
    /// 支給ブキ
    case StageScheduleSuppliedWeapons
    /// スケジュール
    case StageScheduleTitle
    /// ルールごとの勝率
    case StageScheduleWinRateByRules
    /// Xマッチ
    case StageScheduleXmatch
}
