name: CI 

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Cache CDK Dependencies
        uses: actions/cache@v3
        id: cache_cdk_dependency_id
        env:
          cache-name: cache-cdk-dependency
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('bun.lockb') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        # if: ${{ steps.cache_cdk_dependency_id.outputs.cache-hit != 'true' }}
        run: bun install

      - name: Format
        run: bun format
      
      - name: Lint
        run: bun lint 
      
      - name: Build
        run: bun dev
